[package]
name = "epicinium_lib"
version = "0.35.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]
edition = "2018"

[features]

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
log = "*"
libc = "*"
